[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--prefix=/opt/buildhome/node_modules"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true